### ISSUE TITLE
Treeshaking

### ISSUE THREAD

**Issue by SDesya74** [krowten/svelte-heroicons#1]
Hello! Thank you so much for such a good library! It is very easy to learn and easy to use.

I found a small problem: one-time loading of the entire set of icons, instead of loading only those that are actually used.

Case 1. When I use ```Icon.svelte``` component, I see a big **icon-set.js** loading.

Case 2. When I write ```import { LogoutIcon } from "@krowten/svelte-heroicons";``` I see a bunch of small (~2ms) single icon loadings.

So far I have found a way to fix this with ```import LogoutIcon from "@krowten/svelte-heroicons/icons/LogoutIcon.svelte";``` but it seems too cumbersome to me.

Is there any way to add tree shaking for case 2?

Thanks in advance :)

**Comment by krowten** [comment]
Hello. if you use sveltekit, try this case in a finished build after executing the commands: npm run build && npm run preview.
